core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('accounts/', include('account.urls')),
    path('shopping-list/', include('shopping_list.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/shopping-list/', include('shopping_list.urls_api')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_list/urls.py
from django.urls import path

from shopping_list.views import ShoppingListView, ItemListView, \
    ShoppingListCreateView, ShoppingListSingle

urlpatterns = [
    path('lists/', ShoppingListView.as_view(), name='shopping_list'),
    path('lists/create/', ShoppingListCreateView.as_view(),
         name='shopping_list_create'),
    path('lists/<int:pk>/', ShoppingListSingle.as_view(),
         name='shopping_list_single'),
    path('items/', ItemListView.as_view(), name='items')
]

shopping_list/models.py
import logging

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from account.models import Profile, User
from core.models import SoftDeleteModel
from items.models import Item
from utils.send_mail import send_mail

logger = logging.getLogger('shoppero')


class ShoppingList(SoftDeleteModel):
    """Shopping list object"""
    name = models.CharField(_('shopping list name'), max_length=100,
                            blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(_('creation date'), auto_now_add=True)

    class Meta:
        db_table = 'shopping_list'

    def __str__(self):
        return self.name


class ShoppingListItem(models.Model):
    """Object for connecting items and shopping lists"""
    shopping_list = models.ForeignKey(ShoppingList, null=True, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, blank=True, null=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE, related_name='creator')
    editor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='editor')
    is_done = models.BooleanField(default=False)
    quantity = models.DecimalField(max_digits=4, decimal_places=2, default=1, validators=[MinValueValidator(0)])
    price = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True,
                                validators=[MinValueValidator(0)])

    class Meta:
        db_table = 'shopping_list_item'

    def __str__(self):
        return f'{self.shopping_list.name} : {self.item.name}'


class SharedShoppingList(models.Model):
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    email = models.EmailField(null=True, blank=True)
    access_level = models.CharField(choices=Profile.SHARE_LEVEL_CHOICES, default=Profile.READ_ACCESS, max_length=10)

    class Meta:
        db_table = 'shared_shopping_list'

    def __str__(self):
        return f'{self.get_email()} - {self.shopping_list.name}'

    def get_email(self):
        if self.user:
            return self.user.email
        return self.email


class Category(SoftDeleteModel):
    name = models.CharField(_('item category'), max_length=30)

    def __str__(self):
        return self.name


@receiver(post_save, sender=SharedShoppingList)
def share_shopping_list_signal(sender, instance: SharedShoppingList, created, **kwargs):
    """Inform user via mail that someone shared a list with them"""
    logger.info('Sending mail for shared list')
    if created:
        list_owner = instance.shopping_list.user
        email = instance.get_email()
        # TODO replace placeholder url with proper url leading to list
        url = reverse('shopping_list_single', args=[instance.shopping_list.id])
        subject = _('New shared shopping list')
        message = render_to_string('mail/shared_list.html', {
            'email': email,
            'sender': list_owner,
            'list_url': url
        })
        send_mail(subject, message, [email])

shopping_list/forms.py
from django import forms

from shopping_list.models import ShoppingList, ShoppingListItem, \
    SharedShoppingList


class ShoppingListForm(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(ShoppingListForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''


class ShoppingListItemForm(forms.ModelForm):
    class Meta:
        model = ShoppingListItem
        fields = ('item', 'is_done', 'quantity', 'price')

    def __init__(self, *args, **kwargs):
        super(ShoppingListItemForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''


class SharedShoppingListForm(forms.ModelForm):
    class Meta:
        model = SharedShoppingList
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SharedShoppingListForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''

shopping_list/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import TemplateView
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ViewSet, ModelViewSet

from items.forms import ItemForm
from shopping_list.forms import ShoppingListForm, \
    ShoppingListItemForm, SharedShoppingListForm
from shopping_list.models import Item, ShoppingList
from shopping_list.querysets import get_shopping_list_items_queryset
from shopping_list.serializers import item_to_dict, \
    ShoppingListDetailsSerializer, ShoppingListSerializer, \
    ItemAutocompleteSerializer, ItemSerializer
from shopping_list.utils import tags_string_to_list, add_tag_to_item

logger = logging.getLogger('shoppero')


class ShoppingListView(TemplateView):
    template_name = 'shopping_list/shopping_lists.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ShoppingListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ShoppingListView, self).get_context_data(**kwargs)
        result = get_shopping_list_items_queryset(self.request.user.id)
        context.update({'shopping_lists': result})
        return context


class ShoppingListCreateView(TemplateView):
    template_name = 'shopping_list/shopping_list_create.html'
    list_form = ShoppingListForm
    shopping_list_item_form = ShoppingListItemForm
    item_form = ItemForm
    shared_list_form = SharedShoppingListForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ShoppingListCreateView, self).dispatch(request, *args,
                                                            **kwargs)


class ShoppingListSingle(View):
    template_name = 'shopping_list/shopping_list_create.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ShoppingListSingle, self).dispatch(request, *args,
                                                        **kwargs)

    def get_initial_context(self, pk):
        s_list = get_object_or_404(ShoppingList, pk=pk, user=self.request.user,
                                   deleted__isnull=True)
        return {'list': s_list}

    def get(self, request, pk):
        context = self.get_initial_context(pk)
        rendered = render(request, self.template_name, context)
        return HttpResponse(rendered)


class ItemListView(View):
    _template_name = 'shopping_list/item_list.html'
    _form_class = ItemForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ItemListView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        logger.info('User %d requesting item list', request.user.id)
        order_param = request.GET.get('order_by', 'id')
        items = Item.objects.filter(
            deleted__isnull=True,
            user=request.user
        ).all().order_by(
            order_param)
        context = {'items': items}
        return HttpResponse(render(request, self._template_name, context))

    def post(self, request):
        logger.info('Creating new item for user %d', request.user.id)
        logger.info(request.POST)
        form = self._form_class(request.POST)
        if form.is_valid():
            tags = form.cleaned_data.pop('tags', '')
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            tag_list = tags_string_to_list(tags)
            instance = add_tag_to_item(instance, tag_list)
            instance.refresh_from_db()
            context = {
                'status': 'success',
                'message': _('Item created'),
                'content': item_to_dict(instance)
            }
        else:
            logger.info('Item creation failed: %s', form.errors)
            context = {
                'status': 'error',
                'message': _('Submission error'),
                'content': form.errors
            }
        return JsonResponse(context, safe=False)


class ShoppingListViewSet(ViewSet):
    _serializer = ShoppingListSerializer
    _serializer_details = ShoppingListDetailsSerializer

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ShoppingListViewSet, self).dispatch(request, *args,
                                                         **kwargs)

    def create(self, request):
        logger.info(f'User {request.user} creating a new list')
        logger.info(request.data)
        serializer = self._serializer(data=request.data,
                                      context={'request': request})
        if serializer.is_valid():
            messages.success(request, _('List saved'))
            instance = serializer.save()
            return Response({
                'status': 'success',
                'url': reverse('shopping_list_single', args=[instance.pk]),
                'content': serializer.data
            })
        else:
            logger.info(serializer.errors)
            context = {'errors': serializer.errors}
            if 'items' in serializer.errors:
                message = serializer.errors['items'][0]
                context['message'] = message
            return Response(context, status=status.HTTP_400_BAD_REQUEST)

    def update(self, request, pk):
        logger.info(f'User {request.user} updating list {pk}')
        logger.info(request.data)
        instance = get_object_or_404(ShoppingList, pk=pk, deleted__isnull=True)
        serializer = self._serializer(instance, data=request.data,
                                      context={'request': request})
        if serializer.is_valid():
            serializer.save()
            messages.success(request, _('Shopping list update'))
            return Response({
                'status': 'success',
                'url': reverse('shopping_list')
            })
        else:
            logger.info(serializer.errors)
            context = {'errors': serializer.errors}
            if 'items' in serializer.errors:
                message = serializer.errors['items'][0]
                context['message'] = message
            return Response(context, status=status.HTTP_400_BAD_REQUEST)

    def archive(self, request, pk):
        logger.info(u'User %d archiving list %d', request.user.id, pk)
        item = get_object_or_404(ShoppingList, pk=pk, user=request.user,
                                 deleted__isnull=True)
        item.soft_delete()
        result = get_shopping_list_items_queryset(request.user.id)
        serializer = self._serializer_details(result, many=True)
        data = serializer.data
        for i in range(0, len(data)):
            data[i]['url'] = reverse('api_shopping_list_single',
                                     args=[data[i]['id']])
        return Response({'status': 'success', 'content': data})

    def delete(self, request, pk, ):
        logger.info(u'User %d deleting list %d', request.user.id, pk)
        item = get_object_or_404(ShoppingList, pk=pk, user=request.user,
                                 deleted__isnull=True)
        item.delete()
        result = get_shopping_list_items_queryset(request.user.id)
        serializer = self._serializer_details(result, many=True)
        data = serializer.data
        for i in range(0, len(data)):
            data[i]['url'] = reverse('api_shopping_list_single',
                                     args=[data[i]['id']])
        return Response({'status': 'success', 'content': data})


class ItemViewSet(ModelViewSet):
    serializer_class = ItemSerializer
    autocomplete_serializer_class = ItemAutocompleteSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return self.request.user.item_set.filter(deleted__isnull=True).all()

    def get_serializer_context(self):
        context = super(ItemViewSet, self).get_serializer_context()
        context.update({'request': self.request})
        return context

    @action(detail=True, method=['patch'])
    def archive(self, request, pk=None):
        logger.info('User %d deleting item %d', request.user.id, pk)
        instance = self.get_object()
        instance.soft_delete()
        instance.save()
        context = {'status': 'success', 'message': _('Item deleted')}
        return JsonResponse(context)

    def update(self, request, *args, **kwargs):
        logger.info('User %d updating item', request.user.pk)
        res = super(ItemViewSet, self).update(request, *args, **kwargs)
        res.data.update({
            'url': reverse('api_item_single', args=[res.data['id']])
        })
        return res

    def create(self, request, *args, **kwargs):
        logger.info('User %d creating item %s', request.user.pk, request.data)
        res = super(ItemViewSet, self).create(request, *args, **kwargs)
        res.data.update({
            'url': reverse('api_item_single', args=[res.data['id']])
        })
        return res

    def autocomplete(self, request):
        name = request.GET.get('name', '')
        if len(name) < 2:
            return JsonResponse([], status=200)
        items = Item.objects.filter(name__icontains=name,
                                    deleted__isnull=True).all()
        serializer = self.autocomplete_serializer_class(items, many=True)
        return JsonResponse(serializer.data, safe=False)

templates/shopping_list/elements/share_with_user_card.html
<div id="shared-mail-body" class="card flex-fill mt-sm-3 mt-md-0 ml-md-4 border-secondary px-3">
    <div id="shared-mail-header" class="header border-bottom border-secondary">
        <h5>Share with user</h5>
    </div>
    <div class="body pt-3 pb-1">
        <form id="share-list-form">
            <label for="email" class="sr-only">Email</label>
            <div class="input-group">
                <input id="email" type="email" class="form-control" placeholder="Share list with email...">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit" id="email-btn">
                        Add email
                    </button>
                </div>
            </div>
            <div id="email_errors" class="error"></div>
        </form>
        <div id="email-list" class="mt-2" style="max-height: 127px !important; overflow: auto;">
            <table id="email" class="table m-0">
                <tbody>
                {% for share in list.sharedshoppinglist_set.all %}
                    <tr {% if forloop.last %}id="last"{% endif %}>
                        <td class="email" data-email="{{ share.get_email | lower }}">{{ share.get_email | lower }}</td>
                        <td class="w-3-rem i-btn delete-mail">
                            <i class="fas fa-trash-alt"></i>
                        </td>
                    </tr>
                {% empty %}
                    {% include 'shared/empty_table_row.html' with colspan=2 message="No emails" %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

templates/shopping_list/elements/shopping_list_form_card.html
<div class="card col-md-7 d-inline-block border-secondary px-3">
    <div id="shopping-list-card-header" class="header border-bottom border-secondary">
        <h5>Create shopping list</h5>
    </div>
    <div id="shopping-list-card-body" class="body py-3">
        <form id="shopping-list-item-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="name" class="sr-only">
                    Shopping list name</label>
                <input id="name" type="text" class="form-control" placeholder="Shopping list name"
                       value="{{ list.name }}" autofocus>
                <div id="name_errors" class="error pl-3"></div>
            </div>
            <hr>
            <div class="form-group mb-4">
                <div class="col-8 d-inline-block p-0">
                    <label for="item-name" class="sr-only">Item name</label>
                    <datalist id="item-datalist"></datalist>
                    <input id="item-name" type="text" class="form-control" placeholder="Item name" maxlength="200"
                           list="item-datalist" data-url="{% url 'api_item_autocomplete' %}" required>
                    <div id="item-name_errors" class="error"></div>
                </div>
                <div class="d-inline col-3 float-right p-0">
                    <label for="quantity" class="sr-only">Item quantity</label>
                    <input id="quantity" type="number" step="0.01" class="form-control"
                           max="99.99" placeholder="Quantity" min="0">
                    <div id="quantity_errors" class="error"></div>
                </div>
            </div>
            <div class="col-3 d-inline-block p-0 mr-3">
                <label for="price" class="sr-only">Item Price</label>
                <input id="price" type="number" step="0.01" class="form-control"
                       placeholder="Item price" min="0" max="9999999.99">
                <div id="price_errors" class="error"></div>
            </div>
            <div class="col-4 d-inline-block p-0 mr-3">
                <label for="code" class="sr-only">Item code</label>
                <input id="code" type="text" class="form-control" placeholder="Item code" maxlength="20">
                <div id="code_errors" class="error"></div>

            </div>
            <div class="col-2 d-inline-block p-0">
                <div class="custom-control custom-switch">
                    <input class="custom-control-input" type="checkbox" id="is-done">
                    <label class="custom-control-label" for="is-done">Done?</label>
                </div>
            </div>
            <div class="col-2 d-inline p-0">
                <button id="add-item" type="submit" class="btn btn-primary float-right">
                    Add item
                </button>
            </div>
        </form>
    </div>
</div>

templates/shopping_list/elements/shopping_list_table.html
<section>
    <table id="items" class="table">
        <thead>
        <tr>
            <th>Item</th>
            <th style="width: 25%">Code</th>
            <th style="width: 10%">Quantity</th>
            <th style="width: 10%">Price</th>
            <th style="width: 10%">Completed</th>
            <th style="width: 10%">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for list_item in list.shoppinglistitem_set.all %}
            <tr class="data" {% if forloop.last %}id="last"{% endif %} data-item-id="{{ list_item.item.id }}" data-link="{{ list_item.id }}">
                <td class="item-name" data-value="{{ list_item.item.name }}">{{ list_item.item.name }}</td>
                <td class="item-code" data-value="{{ list_item.item.code }}">{{ list_item.item.code }}</td>
                <td class="item-quantity" data-value="{{ list_item.quantity }}">{{ list_item.quantity }}</td>
                <td class="item-price" data-value="{{ list_item.price }}">
                    {% if list_item.price %}
                        {{ list_item.price }}{% endif %}</td>
                <td class="i-btn item-done toggle-done justify-text-center" data-value="{{ list_item.is_done }}">
                    {% if list_item.is_done %}
                        <i class="fa-15x text-success fas fa-check-circle"></i>{% else %}
                        <i class="fa-15x text-danger far fa-times-circle"></i>{% endif %}
                </td>
                <td class="item-action">
                    <span class="i-btn edit-item-row"><i class="fas fa-pen"></i></span>
                    <span class="i-btn delete-item-btn-row"><i class="fas fa-trash-alt"></i></span>
                </td>
            </tr>
        {% empty %}
            {% include 'shared/empty_table_row.html' with colspan=6 message="No items" %}
        {% endfor %}
        </tbody>
    </table>
    <form method="GET" id="edit-row-form"></form>
    <table class="d-none">
        <tr id="template-row">
            <td id="tmpl-name" class="item-name"></td>
            <td id="tmpl-code" class="item-code"></td>
            <td id="tmpl-quantity" class="item-quantity"></td>
            <td id="tmpl-price" class="item-price"></td>
            <td id="tmpl-done" class="item-done"></td>
            <td id="tmpl-action" class="fa-15x item-action">
                <span class="i-btn cancel-btn text-danger"><i class="fas fa-ban"></i></span>
                <button type="submit" form="edit-row-form" class=" btn-link i-btn save-btn text-success">
                    <i class="fas fa-save"></i>
                </button>
            </td>
        </tr>
    </table>
</section>